### ISSUE TITLE
docker-machine hangs on server creation

### ISSUE THREAD

**Issue by optimum-web** [scaleway/docker-machine-driver-scaleway#81] opened 2018-04-18 10:44 UTC
I was able to create instance at scaleway with docker-machine, and i see it in "Running" state  in dashboard however "docker-machine ls" shows me 

```
NAME                   ACTIVE   DRIVER           STATE     URL   SWARM   DOCKER    ERRORS
sample-scaleway4.com            scaleway(VC1S)   Timeout
```
however docker-machine status shows "Running" state
Any hints ?

**Comment by sieben** [comment] 2018-04-18 13:11
Could you provide me information about your scaleway instance through a ticket? https://cloud.scaleway.com/#/tickets Looks like a problem with your instance but not really with docker-machine-driver-scaleway

**Comment by optimum-web** [comment] 2018-04-18 13:38
https://cloud.scaleway.com/#/tickets/ZAIL-0813-NFBY

**Comment by sieben** [comment] 2018-04-19 15:43
Normally the issue should be fixed: https://status.online.net/index.php?do=details&task_id=1229 Could you try again?

**Comment by optimum-web** [comment] 2018-04-20 17:16
No hangs but now I get "Error in driver during machine creation: Quota exceeded for this resource"

**Comment by optimum-web** [comment] 2018-04-20 17:49
web console in dashboard shows empty screen , but machine was created.

**Comment by optimum-web** [comment] 2018-04-21 13:38
Running pre-create checks...
Creating machine...
(scalewaytest10.com) Creating SSH key...
(scalewaytest10.com) Creating server...
(scalewaytest10.com) Starting server...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
.....  Hangs for more than 20 minutes already ...

**Comment by sieben** [comment] 2018-04-21 13:45
Have you tried to connect manually with the SSH command presented in the web console? Is your machine running normally? I'm trying to bisect whether the problem comes from the Scaleway servers not provisioning your machine or your docker-machine not connecting successfully to the instance created.

**Comment by optimum-web** [comment] 2018-04-21 13:50
Yes I tried but get timeout,  in web dashboard I see it in "Running" state. Web console shows nothing. 

https://imgur.com/a/a62KBZr

https://imgur.com/VaG59lu

**Comment by optimum-web** [comment] 2018-04-21 13:52
docker-machine ls
scalewaytest9.com    -        scaleway(VC1S)   Error                   Unknown   "a1540e49-bb94-4ad4-81d5-62c2270d89f2" not found
scalewaytest10.com            scaleway(VC1S)   Timeout

**Comment by sieben** [comment] 2018-04-21 13:55
Could you try to connect with the following command: ssh root@51.15.250.55
If this is not working I would suggest opening a ticket.

**Comment by optimum-web** [comment] 2018-04-21 13:59
Does not work. 
ssh root@51.15.250.55
ssh: connect to host 51.15.250.55 port 22: Connection refused

docker-machine ssh scalewaytest9.com
"a1540e49-bb94-4ad4-81d5-62c2270d89f2" not found

root@fb221082681f:/app# docker-machine ssh scalewaytest10.com
exit status 255

**Comment by sieben** [comment] 2018-04-21 14:05
I would suggest opening a ticket. Feel free to contact me offline
rleone@online.net

**Comment by optimum-web** [comment] 2018-04-21 14:08
Can you reopen current issue ?  I have not enough privileges to do it.

**Comment by antapos** [comment] 2018-04-22 21:39
I have the same problem. I opened a support ticket at Scaleway and got the answer shown below which I cannot associate to extra options needed in docker-machine create -d scaleway:
```
Do you the same issue with the rescue mode  because your server is working properly currently ?
https://www.scaleway.com/docs/perform-rescue-action-on-my-server/
```

**Comment by sieben** [comment] 2018-04-23 12:51
I cannot reproduce the problem. If you delete all your machine and starts from 0 are you able to reproduce the problem?

I created a machine using the following command:

```
$ docker-machine create -d scaleway pouet
Running pre-create checks...
Creating machine...
(pouet) Creating SSH key...
(pouet) Creating server...
(pouet) Starting server...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env pouet
```
In my environment I got `SCALEWAY_TOKEN`, `SCW_ACCESS_KEY` and `SCALEWAY_ORGANIZATION` defined.

**Comment by sieben** [comment] 2018-04-23 14:05
You can use a 

```
$ curl  -H "X-Auth-Token: token-id" https://cp-par1.scaleway.com/servers 
$ curl  -H "X-Auth-Token: token-id" https://cp-ams1.scaleway.com/servers 

```

**Comment by optimum-web** [comment] 2018-04-23 14:12
I suppose it should be https://cp-ams1.scaleway.com/images  resource, because /servers gives empty list

**Comment by optimum-web** [comment] 2018-04-23 14:15
Anyway,  try use  --scaleway-image="e20532c4-1fa0-4c97-992f-436b8d372c07" and you will be able to reproduce.

**Comment by sieben** [comment] 2018-04-23 14:32
Still cannot reproduce:

```
$ docker-machine create -d scaleway --scaleway-image "e20532c4-1fa0-4c97-992f-436b8d372c07" --scaleway-region "par1" default

Running pre-create checks...
Creating machine...
(default) Creating SSH key...
(default) Creating server...
(default) Starting server...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env default
```

**Comment by antapos** [comment] 2018-04-23 14:52
I installed docker-machine-driver-scaleway using

```shell
# install latest (git) version of docker-machine-driver-scaleway
$ brew tap scaleway/scaleway
$ brew install scaleway/scaleway/docker-machine-driver-scaleway --HEAD
```

I created the machine using the following command:
```shell
    docker-machine create -d scaleway \
      --scaleway-organization=$SCALEWAY_ACCESS_KEY \
      --scaleway-token=$SCALEWAY_TOKEN \
      --scaleway-name="$MACHINE_NAME" \
      --scaleway-region=$SCALEWAY_REGION \
      --scaleway-commercial-type=$SCALEWAY_COMMERCIAL_TYPE \
      --scaleway-image=$SCALEWAY_IMAGE \
      $MACHINE_NAME
```

where SCALEWAY_REGION was tested with am1, par1, SCALEWAY_COMMERCIAL_TYPE=VC1S, SCALEWAY_IMAGE was tested with docker and the ubuntu-xenial

**Comment by antapos** [comment] 2018-04-23 14:53
The problem was due to using `docker` as default boot image and was resolved after changing it to `mainline` from the Scaleway console

**Comment by sieben** [comment] 2018-04-23 15:51
@antapos @optimum-web Do you still currently experience problems? Can this issue be closed?

**Comment by optimum-web** [comment] 2018-04-23 15:53
I just tried to create once again.  I used same command  like  @antapos  commented above and same result.  options: ['docker-machine', 'create', '--driver=scaleway', '--scaleway-name', 'sample-scaleway11.com', '--scaleway-organization', '***********, '--scaleway-token', '*************', '--scaleway-image', 'e20532c4-1fa0-4c97-992f-436b8d372c07', '--scaleway-commercial-type', 'C2S', 'sample-scaleway11.com'
 
NAME                    ACTIVE   DRIVER           STATE     URL   SWARM   DOCKER    ERRORS
sample-scaleway11.com            scaleway(C2S)    Timeout

Secondly I received this:  Error in driver during machine creation: No such image: ubuntu-xenial

**Comment by antapos** [comment] 2018-04-23 15:54
@sieben it was opened by @optimum-web not me. I found it and added comments because I had the same problem. I will try it again tonight on my other laptop which had the problem and let you know.

**Comment by optimum-web** [comment] 2018-04-23 16:03
I tried additionally "docker" image  and received 1: Error creating machine: Error in driver during machine creation: Too many candidates for docker (2)

**Comment by sieben** [comment] 2018-04-23 16:04
Indeed, docker-machine generates SSH keys. That being said, if your server doesn't have a public IP after being created, SSH client cannot connect. If I use your command, there is no IP that is by default assigned on the server.

**Comment by optimum-web** [comment] 2018-04-23 18:00
Finally it worked !  I changed  commercial type to VCS1.

**Comment by optimum-web** [comment] 2018-04-23 18:03
The worst thing is that I still don't understand the reason of all previous fails.

**Comment by sieben** [comment] 2018-04-23 18:12
docker-machine only send simple HTTPS requests to our APIs. I think the bug
mostly come from different code paths between baremetal instances and
virtual instances. I will keep on investigate and try to reproduce your
bug. Is it fine to close the issue now?

**Comment by optimum-web** [comment] 2018-04-23 18:13
Yes, sure

**Closed** 2018-04-23 18:14 UTC

**Comment by antapos** [comment] 2018-04-23 21:44
The problem insists. The strange thing is that executing the exact same docker-machine create command sometimes fails and sometimes it works!

**Comment by sieben** [comment] 2018-04-24 08:09
@antapos What are the typical stacktraces that you get? Do you have a wide variety of errors kind?

**Comment by antapos** [comment] 2018-04-24 08:26
@sieben Another way to fix the problem is to turn ON the 'ENABLE LOCAL BOOT':
<img width="756" alt="2018-04-24 11 24 25" src="https://user-images.githubusercontent.com/1324326/39175177-4f2ed76c-47b2-11e8-895a-f3c80c6fa051.png">

**Comment by optimum-web** [comment] 2018-07-30 11:32
@antapos  Is it possible to set  "ENABLE LOCAL BOOT" to "ON"  through API  ?

**Comment by optimum-web** [comment] 2018-07-30 11:33
I still getting weird errors like  "no such boot script Docker "
